import QtQuick
import QtMultimedia

// Loud-alarm tone (design §3.2). Only compiled in with RC_UI_SOUND.
// resources/alarm.wav is generated by tools/gen_alarm_wav.py.
Item {
    id: root
    property bool active: false

    SoundEffect {
        id: tone
        source: "qrc:/qt/qml/RcUi/resources/alarm.wav"
        loops: SoundEffect.Infinite
        volume: 1.0
    }
    onActiveChanged: active ? tone.play() : tone.stop()
    Component.onCompleted: if (active) tone.play()
}
