#!/usr/bin/env bash
# Convert a PanCho "ScreenFiles/Panel N/mipi-panel.dtbo" into an editable panel amendment
# (panels/panelN.dtsi) that build.sh merges into the kernel dtb at build time.
#
# Only the panel node's compatible and panel_description are taken. The rest of the
# Panel 0 overlay (reset gpio, joypad inversion) is already in the r36s base dtb,
# and its adc-keys / lcd-rst fragments target nodes that don't exist there.
#
# usage: extract-panel.sh <mipi-panel.dtbo> > panels/panelN.dtsi
set -euo pipefail

dtbo=${1:?usage: extract-panel.sh <mipi-panel.dtbo>}
dts=$(dtc -q -I dtb -O dts "$dtbo")

compatible=$(sed -n 's/^[[:space:]]*compatible = "\([^"]*\)";/\1/p' <<<"$dts" | head -n1)
description=$(sed -n 's/^[[:space:]]*panel_description = \(.*\);$/\1/p' <<<"$dts" | head -n1)
[[ -n $compatible && -n $description ]] || { echo "no panel node in $dtbo" >&2; exit 1; }

cat <<EOF
// Generated by extract-panel.sh from $(basename "$(dirname "$dtbo")")/$(basename "$dtbo"); safe to edit.
// panel_description lines: G = geometry/delays/format/lanes, M = display mode, I = init command.

&{/dsi@ff450000/panel@0} {
	compatible = "$compatible";
	panel_description =
		$(sed 's/", "/",\n\t\t"/g' <<<"$description");
};
EOF
